name: Release MattBot

on:
  workflow_dispatch:

env:
  NODE_VERSION: "18.12.1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Build project
        shell: bash
        run: npm run build
      - name: Install Azure CLI
        shell: bash
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Deploy to Azure
        shell: bash
        run: |
          az login --service-principal -u ${{ secrets.AZURE_SP_ID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_SP_TENANT }}
          npm run publish:prod
