name: Release MattBot

on:
  workflow_dispatch:

env:
  NODE_VERSION: "24.18.0"

jobs:
  build-and-deploy:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        shell: bash
        run: npm install
      - name: Build project
        shell: bash
        run: npm run build
      - name: Install Azure CLI
        shell: bash
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure
        shell: bash
        run: |
          npm run publish:prod
